"use strict";
//////問題を配置///////////////////////////////
const questions = [
  { name: "水素", ans: "H" },
  { name: "ヘリウム", ans: "He" },
  { name: "炭素", ans: "C" },
  { name: "窒素", ans: "N" },
  { name: "酸素", ans: "O" },
  { name: "フッ素", ans: "F" },
  { name: "ネオン", ans: "Ne" },
  { name: "ナトリウム", ans: "Na" },
  { name: "マグネシウム", ans: "Mg" },
  { name: "アルミニウム", ans: "Al" },
  { name: "硫黄", ans: "S" },
  { name: "リン", ans: "P" },
  { name: "塩素", ans: "Cl" },
  { name: "アルゴン", ans: "Ar" },
  { name: "カリウム", ans: "K" },
  { name: "カルシウム", ans: "Ca" },
  { name: "金", ans: "Au" },
  { name: "銀", ans: "Ag" },
  { name: "銅", ans: "Cu" },
  { name: "亜鉛", ans: "Zn" },
  { name: "鉛", ans: "Pb" },
  { name: "バリウム", ans: "Ba" },
  { name: "ニッケル", ans: "Ni" },
  { name: "鉄", ans: "Fe" },
  { name: "スズ", ans: "Sn" },
  { name: "白金", ans: "Pt" },
  { name: "水銀", ans: "Hg" },
  { name: "二酸化炭素", ans: "CO2" },
  { name: "水", ans: "H2O" },
  { name: "二酸化硫黄", ans: "SO2" },
  { name: "二酸化窒素", ans: "NO2" },
  { name: "一酸化炭素", ans: "CO" },
  { name: "水素分子", ans: "H2" },
  { name: "窒素分子", ans: "N2" },
  { name: "酸素分子", ans: "O2" },
];
